# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField(default=0)),
                ('time', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.AddField(
            model_name='log',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 19, 33, 28, 673555)),
        ),
        migrations.AddField(
            model_name='track',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
