# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190703_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='sid',
            new_name='llan',
        ),
        migrations.AddField(
            model_name='shangp',
            name='llan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='sname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 19, 50, 41, 335849)),
        ),
        migrations.AlterModelTable(
            name='track',
            table='track',
        ),
    ]
