# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190703_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 20, 59, 16, 753205)),
        ),
    ]
