# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190703_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='zt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 19, 49, 58, 176445)),
        ),
    ]
