# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190704_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parentid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 8, 45, 32, 176266)),
        ),
    ]
