# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190705_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 9, 58, 49, 772586)),
        ),
    ]
