# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 02:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190705_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 5, 10, 48, 21, 497592), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 48, 21, 500595)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 48, 21, 496590)),
        ),
    ]
