# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190705_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='istu',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 5, 14, 39, 29, 236497), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 14, 39, 29, 240521)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 14, 39, 29, 235497)),
        ),
    ]
