# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190705_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='gid',
        ),
        migrations.AddField(
            model_name='shangp',
            name='bianhao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='bh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 6, 10, 53, 7, 446020), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 10, 53, 7, 449539)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 10, 53, 7, 445520)),
        ),
    ]
