# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190706_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 6, 14, 4, 22, 357804), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 14, 4, 22, 361307)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 14, 4, 22, 356805)),
        ),
    ]
