# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190706_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 9, 10, 54, 31, 570629), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 10, 54, 31, 570629)),
        ),
        migrations.AlterField(
            model_name='size',
            name='gid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 10, 54, 31, 570629)),
        ),
    ]
