# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190709_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='xname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 9, 10, 59, 57, 883864), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 10, 59, 57, 886867)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 10, 59, 57, 882864)),
        ),
    ]
