# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190709_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='zh',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 9, 14, 35, 28, 134278), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 14, 35, 28, 137279)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 14, 35, 28, 132277)),
        ),
    ]
