# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190709_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 9, 19, 43, 11, 651654), max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderState',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 19, 43, 11, 655156)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 19, 43, 11, 650653)),
        ),
    ]
