# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190709_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=500, null=True)),
                ('path', models.CharField(max_length=50)),
                ('time', models.DateTimeField(max_length=30, null=True)),
                ('isli', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'eval',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('path', models.CharField(max_length=30, null=True)),
                ('keyword', models.CharField(max_length=50, null=True)),
                ('filepath', models.CharField(max_length=50, null=True)),
                ('nei', models.CharField(max_length=300, null=True)),
                ('ban', models.CharField(max_length=100, null=True)),
                ('bei', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'system',
            },
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 9, 20, 41, 14, 340203), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 20, 41, 14, 343208)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 20, 41, 14, 338704)),
        ),
        migrations.AddField(
            model_name='eval',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
