# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-10 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190710_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='eval',
            name='tt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 10, 9, 27, 21, 864704), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 9, 27, 21, 866705)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 9, 27, 21, 863704)),
        ),
    ]
