# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-10 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190710_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xiang',
            fields=[
                ('xid', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'xiang',
            },
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 10, 15, 37, 47, 22110), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 15, 37, 47, 25615)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 15, 37, 47, 21110)),
        ),
    ]
