# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-11 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190710_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isfu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='kuai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='kuainame',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 11, 16, 58, 46, 862525), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 16, 58, 46, 865527)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 16, 58, 46, 860525)),
        ),
    ]
