# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-12 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190711_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangp',
            name='path',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='manage',
            name='time',
            field=models.CharField(default=datetime.datetime(2019, 7, 12, 8, 8, 25, 972582), max_length=30),
        ),
        migrations.AlterField(
            model_name='shangp',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 8, 8, 25, 979088)),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 8, 8, 25, 971586)),
        ),
    ]
